# -*- coding: utf-8 -*-
"""AMA_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-M5IOi2sSUAarvUnV7lqaXdljgoKPJr5

# Importações
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler, MultiLabelBinarizer
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    hamming_loss,
    accuracy_score,
    precision_recall_curve
)
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
import tensorflow as tf
import math
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping

"""# Analisando e importando o dataset"""

file_id = "1SUFw2FScB_VVktuEAN5be8TcwaLL1ySD"
download_url = f"https://drive.google.com/uc?export=download&id={file_id}"

spotify_dataset = pd.read_csv(download_url)

duplicated_all = spotify_dataset[spotify_dataset.duplicated(subset = 'track_id', keep=False)]
duplicated = spotify_dataset[spotify_dataset.duplicated(subset = 'track_id', keep='first')]

print(f'''Unique Duplicates: {duplicated.shape[0]}
Total Duplicates: {duplicated_all.shape[0]}
Total spotify_data: {spotify_dataset.shape[0]}
Duplicates %: {round(duplicated_all.shape[0]/spotify_dataset.shape[0]*100, 2)}''')

spotify_dataset[spotify_dataset['track_id'] == duplicated['track_id'].iloc[0]]

spotify_df = spotify_dataset
spotify_df = spotify_df.drop_duplicates(subset='track_id', keep='first').reset_index(drop=True)

print("Após remoção:")
print(f"Total de registros: {spotify_df.shape[0]}")
print(f"Duplicados restantes: {spotify_df.duplicated(subset='track_id').sum()}")

coluna_n_util = ['artist_name', 'track_name', 'track_id']
spotify_df = spotify_df.drop(columns=coluna_n_util).reset_index(drop=True)
spotify_df.head()

mode_dict = {'Major' : 1, 'Minor' : 0} #Binario
key_dict = {'C' : 1, 'C#' : 2, 'D' : 3, 'D#' : 4, 'E' : 5, 'F' : 6,
        'F#' : 7, 'G' : 8, 'G#' : 9, 'A' : 10, 'A#' : 11, 'B' : 12} # É pq na vida real é uma sequencia musical de notas
# no time_sig.. deixei só o dominador sla, o de cima kkkk
spotify_df['time_signature'] = spotify_df['time_signature'].apply(lambda x : int(x[0]))
spotify_df['mode'] = spotify_df['mode'].replace(mode_dict)
spotify_df['key'] = spotify_df['key'].replace(key_dict).astype(int)

spotify_df.head()

print(pd.isnull(spotify_df).sum())

fig, axes = plt.subplots(1, 2, figsize=(8, 5))

sns.countplot(y="genre", data=spotify_dataset, color='green', ax=axes[0])
axes[0].set_title('Original')

sns.countplot(y="genre", data=spotify_df, color='green', ax=axes[1])
axes[1].set_title('Após Limpeza')

plt.tight_layout()
plt.show()

replace_dict = {
    'A Capella': 'Classical',
    "Children’s Music": "Children's Music",

    'Alternative': 'Indie/Alternative',
    'Indie': 'Indie/Alternative',
}

spotify_dataset['genre'] = spotify_dataset['genre'].replace(replace_dict)

fig, axes = plt.subplots(1, 2, figsize=(8, 5))

sns.countplot(y="genre", data=spotify_df, color='green', ax=axes[0])
axes[0].set_title('Original')

sns.countplot(y="genre", data=spotify_dataset, color='green', ax=axes[1])
axes[1].set_title('Após Reorganização')

plt.tight_layout()
plt.show()

spotify_df_limpo = spotify_df

print(f'Número de linhas: {spotify_df.shape[0]}')
print(f'Número de linhas: {spotify_dataset.shape[0]}')

importances = rfc.feature_importances_
for feat, imp in zip(X.columns, importances):
    print(f"{feat}: {imp:.4f}")

"""# RandomForestClassifier"""

rfc_set = spotify_dataset.copy()
key_dict = {'C' : 1, 'C#' : 2, 'D' : 3, 'D#' : 4, 'E' : 5, 'F' : 6,
        'F#' : 7, 'G' : 8, 'G#' : 9, 'A' : 10, 'A#' : 11, 'B' : 12}
rfc_set['key'] = rfc_set['key'].replace(key_dict).astype(int)

X = rfc_set.drop(columns=['genre','popularity','time_signature', 'mode', 'artist_name', 'track_name', 'track_id'])
y = rfc_set['genre']

le = LabelEncoder()
y_encoded = le.fit_transform(y)

random_state = 11
test_size = 0.2
X_train, X_valid, y_train, y_valid = train_test_split(X, y_encoded, test_size=test_size, random_state=random_state)

rfc = RandomForestClassifier(n_estimators=100, random_state=42)
rfc.fit(X_train, y_train)

y_rfc = rfc.predict(X_valid)

print(classification_report(y_valid, y_rfc, target_names=le.classes_))

report_dict = classification_report(y_valid, y_rfc, target_names=le.classes_, output_dict=True)

df_report = pd.DataFrame(report_dict).transpose()
df_report = df_report.drop(['accuracy', 'macro avg', 'weighted avg'], errors='ignore')


metrics_to_plot = ['precision', 'recall', 'f1-score']
df_metrics = df_report[metrics_to_plot]

# Plota o heatmap
plt.figure(figsize=(10, 12))
sns.heatmap(df_metrics, annot=True, fmt=".2f", cmap="YlGnBu")
plt.title("Classification Report (Precision, Recall, F1-score)")
plt.xlabel("Metric")
plt.ylabel("Class")
plt.tight_layout()
plt.show()

"""*RandomForestClassifier* usando Multilabel"""

spotify_dataset['genre'] = spotify_dataset['genre'].replace(replace_dict)
spotifY_rfc_ml = spotify_dataset.drop_duplicates(subset=['genre', 'track_id'], keep='first')

# Agrupa gêneros por track_id
grouped = spotifY_rfc_ml.groupby('track_id').agg({
    'genre': lambda x: list(set(x)),
    **{col: 'first' for col in spotifY_rfc_ml.columns if col not in ['track_id', 'genre']}
}).reset_index()

# Binariza os gêneros (multilabel)
mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(grouped['genre'])

df = grouped.drop(columns=['genre', 'track_id', 'artist_name', 'track_name','popularity','time_signature', 'mode'])
df['key'] = df['key'].replace(key_dict).astype(int)

X_train, X_test, Y_train, Y_test = train_test_split(df, Y, test_size=0.2, random_state=42)

base_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    class_weight='balanced'
)
model = MultiOutputClassifier(base_model)

model.fit(X_train, Y_train)
Y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score, hamming_loss, jaccard_score, classification_report

exact_match_ratio = accuracy_score(Y_test, Y_pred)

loss = hamming_loss(Y_test, Y_pred)
print(f"Perda de Hamming (Hamming Loss): {loss:.4f}\n")

print(f"Taxa de Acerto Exato (Exact Match Ratio): {exact_match_ratio:.4f}\n")
jaccard = jaccard_score(Y_test, Y_pred, average='samples')

print(f"Pontuação Jaccard (média por amostra): {jaccard:.4f}\n")

print(classification_report(Y_test, Y_pred, target_names=mlb.classes_, zero_division=0))

# --- Configuração dos Subplots ---
labels = mlb.classes_
n_labels = len(labels)

n_cols = 4
n_rows = math.ceil(n_labels / n_cols)

fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 4, n_rows * 3.5))

axes = axes.flatten()

# --- Loop para plotar cada matriz ---
for i, label in enumerate(labels):
    ax = axes[i]
    cm = confusion_matrix(Y_test[:, i], Y_pred[:, i])

    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', ax=ax,
                xticklabels=['Não ' + label, label],
                yticklabels=['Não ' + label, label])

    ax.set_title(f'Matriz para: {label}', fontsize=12)
    ax.set_xlabel('Previsto')
    ax.set_ylabel('Verdadeiro')

# Oculta os eixos extras que não foram usados
for i in range(n_labels, len(axes)):
    axes[i].axis('off')

# Ajusta o layout para evitar sobreposição de títulos e rótulos
plt.tight_layout()
plt.show()

num_labels_per_song = Y.sum(axis=1)
plt.hist(num_labels_per_song, bins=range(1, num_labels_per_song.max()+2))
plt.title('Número de gêneros por música')
plt.xlabel('Número de rótulos')
plt.ylabel('Número de músicas')
plt.show()

"""# Rede neural"""

# Dicionários para codificação
mode_dict = {'Major' : 1, 'Minor' : 0}
key_dict = {'C' : 1, 'C#' : 2, 'D' : 3, 'D#' : 4, 'E' : 5, 'F' : 6,
            'F#' : 7, 'G' : 8, 'G#' : 9, 'A' : 10, 'A#' : 11, 'B' : 12}

spotify_rede = spotify_dataset.copy()
spotify_rede['key'] = spotify_rede['key'].replace(key_dict)
spotify_rede['genre'] = spotify_rede['genre'].replace(replace_dict)

df_multiclass = spotify_rede.drop_duplicates(subset=['track_id'], keep='first')

feature_cols = [
    'acousticness', 'danceability', 'duration_ms', 'energy',
    'instrumentalness', 'key', 'liveness', 'loudness',
    'speechiness', 'tempo', 'valence'
]

X = df_multiclass[feature_cols]
y_labels = df_multiclass['genre']


le = LabelEncoder()
Y = le.fit_transform(y_labels)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42, stratify=Y)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)


print("\n--- Construindo e Compilando o modelo TensorFlow/Keras para Multiclasse ---")

# Define as dimensões de entrada e saída
input_dim = X_train_scaled.shape[1]
output_dim = len(le.classes_)

# Construção do modelo sequencial
model = Sequential([
    Dense(128, activation='relu', input_shape=(input_dim,)),
    Dropout(0.5),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(output_dim, activation='softmax')
])

# Compilação do modelo
model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.summary()

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=15,
    restore_best_weights=True
)

print("\n--- Iniciando Treinamento com TensorFlow/Keras ---")

history = model.fit(
    X_train_scaled,
    Y_train,
    epochs=100,
    batch_size=64,
    validation_data=(X_test_scaled, Y_test),
    callbacks=[early_stopping],
    verbose=1
)

print("\n--- Avaliando o modelo multiclasse ---")

# O método .predict() retorna as probabilidades para cada classe
y_pred_proba = model.predict(X_test_scaled)

y_pred_classes = np.argmax(y_pred_proba, axis=1)

print(f"\n--- Relatório de Classificação Detalhado ---")
print(classification_report(Y_test, y_pred_classes, target_names=le.classes_, zero_division=0))

history_dict = history.history
train_loss = history_dict['loss']
val_loss = history_dict['val_loss']
train_accuracy = history_dict['accuracy']
val_accuracy = history_dict['val_accuracy']

epochs = range(1, len(train_loss) + 1)
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(16, 6))

ax1.plot(epochs, train_loss, 'bo-', label='Loss de Treino')
ax1.plot(epochs, val_loss, 'ro-', label='Loss de Validação')
ax1.set_title('Curva de Aprendizado: Loss (Erro)')
ax1.set_xlabel('Épocas')
ax1.set_ylabel('Loss')
ax1.legend()
ax1.grid(True)

ax2.plot(epochs, train_accuracy, 'bo-', label='Acurácia de Treino')
ax2.plot(epochs, val_accuracy, 'ro-', label='Acurácia de Validação')
ax2.set_title('Curva de Aprendizado: Acurácia')
ax2.set_xlabel('Épocas')
ax2.set_ylabel('Acurácia')
ax2.legend()
ax2.grid(True)

plt.tight_layout()
plt.show()

"""Rede neural usando Multilabel"""

mode_dict = {'Major' : 1, 'Minor' : 0}
key_dict = {'C' : 1, 'C#' : 2, 'D' : 3, 'D#' : 4, 'E' : 5, 'F' : 6,
            'F#' : 7, 'G' : 8, 'G#' : 9, 'A' : 10, 'A#' : 11, 'B' : 12}

# 1. PREPARAÇÃO E LIMPEZA DOS DADOS (PARA MULTILABEL)
spotify_rede_ml = spotify_dataset.copy()
spotify_rede_ml['key'] = spotify_rede_ml['key'].map(key_dict).fillna(-1).astype(int)
spotify_rede_ml['genre'] = spotify_rede_ml['genre'].replace(replace_dict)

# Isso transforma o problema em multilabel, pois uma música pode ter vários gêneros associados.
genres_per_track = (
    spotify_rede_ml
    .groupby('track_id')['genre']
    .apply(lambda x: list(set(x)))
    .reset_index()
)

features_df = (
    spotify_rede_ml
    .drop(columns=['genre'])
    .drop_duplicates(subset=['track_id'])
    .set_index('track_id')
)

df_multilabel = features_df.join(genres_per_track.set_index('track_id'))

feature_cols = [
    'acousticness', 'danceability', 'duration_ms', 'energy',
    'instrumentalness', 'key', 'liveness', 'loudness',
    'speechiness', 'tempo', 'valence'
]

X = df_multilabel[feature_cols]
y_labels = df_multilabel['genre']

import joblib
mlb = MultiLabelBinarizer()
Y = mlb.fit_transform(y_labels)
joblib.dump(mlb, 'multilabel_binarizer.pkl')


# 2. DIVISÃO EM TREINO E TESTE
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# 3. ESCALONAMENTO DOS DADOS
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 4. CRIAÇÃO E TREINAMENTO DA REDE NEURAL (TENSORFLOW/KERAS)-
print("\n--- Construindo e Compilando o modelo TensorFlow/Keras para Multilabel ---")

# Define as dimensões de entrada e saída
input_dim = X_train_scaled.shape[1]
output_dim = Y.shape[1]

# Construção do modelo sequencial
model = Sequential([
    Dense(256, activation='relu', input_shape=(input_dim,)),
    Dropout(0.5),
    Dense(128, activation='relu'),
    Dropout(0.4),
    Dense(64, activation='relu'),
    Dropout(0.3),
    Dense(output_dim, activation='sigmoid')
])

# Compilação do modelo

label_freq = Y_train.mean(axis=0)
class_weights = 1 / (label_freq + 1e-6)
class_weights = class_weights / class_weights.sum() * len(class_weights)

@tf.function
def weighted_binary_crossentropy(y_true, y_pred):
    weights = tf.constant(class_weights, dtype=tf.float32)
    unweighted_loss = tf.keras.losses.binary_crossentropy(y_true, y_pred)
    weighted_loss = unweighted_loss * weights
    return tf.reduce_mean(weighted_loss)


model.compile(
    optimizer='adam',
    loss = tf.keras.losses.BinaryCrossentropy(label_smoothing=0.1),
    # Métricas comuns para avaliar a performance em tarefas de classificação
    metrics=['accuracy', tf.keras.metrics.Precision(), tf.keras.metrics.Recall()]
)

model.summary()

# O EarlyStopping continua sendo uma ótima prática
early_stopping = EarlyStopping(
    monitor='val_precision',
    mode='max',
    patience=15,
    restore_best_weights=True
)

print("\n--- Iniciando Treinamento com TensorFlow/Keras ---")

# O treinamento é funcionalmente o mesmo
history = model.fit(
    X_train_scaled,
    Y_train,
    epochs=100,
    batch_size=64,
    validation_data=(X_test_scaled, Y_test),
    callbacks=[early_stopping],
    verbose=1
)

print("\n--- Treinamento Concluído ---")

# 5. AVALIAÇÃO CORRETA PARA MULTILABEL
print("\n--- Avaliando o modelo multilabel ---")

# O método .predict() retorna as probabilidades (entre 0 e 1) para cada classe
y_pred_proba = model.predict(X_test_scaled)

# Se a probabilidade for > 0.5, a classe é considerada presente (1), senão ausente (0)

optimal_thresholds = []

for i in range(Y.shape[1]):
    precision, recall, thresholds = precision_recall_curve(Y_test[:, i], y_pred_proba[:, i])
    f1 = 2 * (precision * recall) / (precision + recall + 1e-6)
    best_threshold = thresholds[np.argmax(f1)]
    optimal_thresholds.append(best_threshold)
optimal_thresholds = np.array(optimal_thresholds)
np.save('optimal_thresholds.npy', optimal_thresholds)

y_pred = np.zeros_like(y_pred_proba)

for i, thresh in enumerate(optimal_thresholds):
    y_pred[:, i] = (y_pred_proba[:, i] > thresh).astype(int)

print(f"\n--- Relatório de Classificação Detalhado ---")
# Usamos as classes do MultiLabelBinarizer para os nomes dos alvos
print("Hamming Loss:", hamming_loss(Y_test, y_pred))
print("Accuracy Score:", accuracy_score(Y_test, y_pred))
print(classification_report(Y_test, y_pred, target_names=mlb.classes_))

history_dict = history.history

loss = history_dict['loss']
val_loss = history_dict['val_loss']

accuracy = history_dict['accuracy']
val_accuracy = history_dict['val_accuracy']

precision = history_dict['precision_1']
val_precision = history_dict['val_precision_1']

recall = history_dict['recall_1']
val_recall = history_dict['val_recall_1']

epochs = range(1, len(loss) + 1)

fig, axs = plt.subplots(2, 2, figsize=(18, 12))
fig.suptitle('Curvas de Aprendizado do Modelo Multilabel', fontsize=16)

axs[0, 0].plot(epochs, loss, 'bo-', label='Loss de Treino')
axs[0, 0].plot(epochs, val_loss, 'ro-', label='Loss de Validação')
axs[0, 0].set_title('Curva de Loss (Erro)')
axs[0, 0].set_xlabel('Épocas')
axs[0, 0].set_ylabel('Loss')
axs[0, 0].grid(True)
axs[0, 0].legend()

# Gráfico 2: Acurácia
axs[0, 1].plot(epochs, accuracy, 'bo-', label='Acurácia de Treino')
axs[0, 1].plot(epochs, val_accuracy, 'ro-', label='Acurácia de Validação')
axs[0, 1].set_title('Curva de Acurácia')
axs[0, 1].set_xlabel('Épocas')
axs[0, 1].set_ylabel('Acurácia')
axs[0, 1].grid(True)
axs[0, 1].legend()

# Gráfico 3: Precisão
axs[1, 0].plot(epochs, precision, 'bo-', label='Precisão de Treino')
axs[1, 0].plot(epochs, val_precision, 'ro-', label='Precisão de Validação')
axs[1, 0].set_title('Curva de Precisão')
axs[1, 0].set_xlabel('Épocas')
axs[1, 0].set_ylabel('Precisão')
axs[1, 0].grid(True)
axs[1, 0].legend()

# Gráfico 4: Recall (Sensibilidade)
axs[1, 1].plot(epochs, recall, 'bo-', label='Recall de Treino')
axs[1, 1].plot(epochs, val_recall, 'ro-', label='Recall de Validação')
axs[1, 1].set_title('Curva de Recall')
axs[1, 1].set_xlabel('Épocas')
axs[1, 1].set_ylabel('Recall')
axs[1, 1].grid(True)
axs[1, 1].legend()

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""Analisando os dados"""

plt.figure(figsize=(12,6))
plt.bar(mlb.classes_, Y.sum(axis=0))
plt.xticks(rotation=90)
plt.title("Ocorrências por classe")
plt.show()

genre_df = pd.DataFrame(Y, columns=mlb.classes_)

print("Calculando a matriz de correlação...")
corr_matrix = genre_df.corr()

plt.figure(figsize=(16, 10))  # Tamanho grande para melhor visualização
sns.heatmap(corr_matrix,
            cmap='vlag', # Um bom mapa de cores para correlação (-1: azul, 0: branco, +1: vermelho)
            annot=False) # Não mostramos os números para não poluir o gráfico
plt.title('Matriz de Correlação de Gêneros Musicais', fontsize=20)
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig('correlation_heatmap.png')
print("\nMapa de calor salvo como 'correlation_heatmap.png'")

# Desempilha a matriz para criar uma lista de pares
corr_unstacked = corr_matrix.unstack()
# Ordena os pares pela correlação
sorted_corr = corr_unstacked.sort_values(kind="quicksort", ascending=False)
# Remove correlações de um gênero com ele mesmo (que são sempre 1.0)
sorted_corr = sorted_corr[sorted_corr < 1.0]

print("\n--- Top 10 Pares de Gêneros com Maior Correlação Positiva ---")
# Imprime os 10 primeiros pares (dividido por 2 porque cada par aparece duas vezes, ex: (A,B) e (B,A))
print(sorted_corr.head(20)[::2])